Exception on /download [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/ibrahim/kuffee/main.py", line 203, in download
    return send_file(request.args.get('name'))
  File "/usr/local/lib/python3.10/dist-packages/flask/helpers.py", line 537, in send_file
    return werkzeug.utils.send_file(  # type: ignore[return-value]
  File "/usr/local/lib/python3.10/dist-packages/werkzeug/utils.py", line 440, in send_file
    stat = os.stat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/ibrahim/kuffee/static/files/[Kuffee][دائرية][9x38]OYgPz.eps'
